name: segmenteverygrain

channels:
  - conda-forge

dependencies:
  - python=3.10
  - numpy
  - matplotlib
  - pyqt
  - pandas
  - jupyterlab
  - scipy
  - scikit-image
  - scikit-learn
  - tqdm
  - networkx
  - shapely
  - pip
  - pip:
    - pillow
    - rasterio
    - opencv-python
    - rtree
    - tensorflow<=2.18.1
    - tensorflow-metal
    - torch
    - torchvision
    - sam2
    - segmenteverygrain