name: segmenteverygrain

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - numpy
  - matplotlib=3.7.1
  - pyqt=5.15.7
  - pandas
  - jupyterlab
  - scipy
  - scikit-image
  - scikit-learn
  - tqdm
  - networkx
  - shapely
  - pytorch
  - torchvision
  - pip
  - pip:
    - pillow
    - rasterio
    - opencv-python
    - tensorflow=2.13.0
    - segment-anything
    - segmenteverygrain